### PR TITLE
Fix spelling in readme

### PR DESCRIPTION
**Pull request by timoniq**

### CODE REVIEW

**Comment by jieggii** [comment]
@timoniq r

**Comment by prostomarkeloff** [comment]
No, thank you. Your PR changes some parts that are already okay.

**Comment by jieggii** [comment]
;-;

**Comment by timoniq** [comment]
> No, thank you. Your PR changes some parts that are already okay.

`A most fast`?

**Comment by prostomarkeloff** [comment]
> > No, thank you. Your PR changes some parts that are already okay.
> 
> `A most fast`?

It is.

**Comment by gabbhack** [comment]
@prostomarkeloff hey!

**Comment by gabbhack** [comment]
@prostomarkeloff hey!

**Pull request closed without merging**
